apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: online-shop
spec:
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
